/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prebeeditor;

import javax.swing.JOptionPane;

/**
 *
 * @author rho
 */
public class Login extends javax.swing.JFrame {
    
    final String tituloMarco = "PrebeLogin";

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                setVisible(true);
                setLocationRelativeTo(null);
                setTitle(tituloMarco);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenedorPrincipal = new javax.swing.JPanel();
        iconMan = new javax.swing.JLabel();
        ingresarBtn = new javax.swing.JButton();
        usuarioTf = new javax.swing.JTextField();
        contrasenaPf = new javax.swing.JPasswordField();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        contenedorPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        iconMan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prebeeditor/man-icon.png"))); // NOI18N
        contenedorPrincipal.add(iconMan, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, -1));

        ingresarBtn.setText("Ingresar");
        ingresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarBtnActionPerformed(evt);
            }
        });
        contenedorPrincipal.add(ingresarBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 120, 50));
        contenedorPrincipal.add(usuarioTf, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 210, 40));
        contenedorPrincipal.add(contrasenaPf, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 210, 40));

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/prebeeditor/fondo.png"))); // NOI18N
        contenedorPrincipal.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 522, 466));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenedorPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarBtnActionPerformed
        // TODO add your handling code here:
        char pass[];
        String password;
        pass = contrasenaPf.getPassword();
        password = new String(pass);
        if (usuarioTf.getText().equals("root") && password.equals("toor") ) {
            setVisible(false);
            Editor editor;
            editor = new Editor();
        }else{
            JOptionPane.showMessageDialog(this,"Credenciales incorrectas");
        }
    }//GEN-LAST:event_ingresarBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contenedorPrincipal;
    private javax.swing.JPasswordField contrasenaPf;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel iconMan;
    private javax.swing.JButton ingresarBtn;
    private javax.swing.JTextField usuarioTf;
    // End of variables declaration//GEN-END:variables
}
