Ejercicios de INNER JOIN

a)
SELECT C.CALVE_GRUPO, C.CUPO_MAXIMO, P.MOMBRE, H.DIA_SEMANA, H.HORA_INICIO, H.HORA_FIN
FROM ASIGNATURA A
INNER JOIN CURSO C ON A.ASIGNATURA_ID = C.ASIGNATURA_ID
INNER JOIN PROFESOR P ON C.PROFESOR_ID = P.PROFESOR_ID
INNER JOIN CURSO_HORARIO CH ON C.CURSO_ID = CH.CURSO_ID
INNER JOIN SEMESTRE S ON C.SEMESTRE_ID = S.SEMESTRE_ID
WHERE A.NOMBRE = 'CALCULO 2' AND S.ANIO=2008 AND S.PERIODO = 1		
--Si quitamos el inner, y dejamos join unicamente, ejecua inner join por defecto


b)
SELECT A.NOMBRE, C.CURSO_ID, C.CALVE_GRUPO
FROM ASIGNATURA A
INNER JOIN CURSO C ON A.ASIGNATURA_ID = C.ASIGNATURA_ID
INNER JOIN ESTUDIANTE_INSCRITO EI ON C.CURSO_ID = EI.CURSO_ID
WHERE EI.CALIFICACION IS NULL;


/*

-- Se le conoce como forma anterior--
SELECT ""
FROM ASIGNATURA A, CURSO C, ESTUDIANTE_INSCRITO EI
WHERE A.ASIGNATURA_ID = C.ASIGNATURA_ID
AND C.CURSO_ID = EI.CURSO_ID
AND EI.CALIFICACION IS NULL;

/*

SELECT P.NOMBRE, P.APELLIDO_PATERNO, P.APELLIDO_MATERNO P.RFC, P.FECHA_NACIMIENTO, A.NOMBRE, C.CUPO_MAXIMO, C.PROFESOR, C.CALVE_GRUPO
FROM PROFESOR P
NATURAL JOIN CURSO C ON P.PROFESOR_ID = C.PROFESOR_ID
NATURAL JOIN ASIGNATURA A ON ASIGNATURA_ID = C.ASIGNATURA_ID
WHERE P.APELLIDO_PATERNO = 'KRAUCE'

*/

SELECT *
FROM PROFESOR
NATURAL JOIN CURSO
WHERE PROFESOR.APELLIDO_PATERNO = 'KRAUCE'
